export default {
    FETCH_PROFILE: 'FETCH_PROFILE',
    REMOVE_PROFILE: 'REMOVE_PROFILE',
    FETCH_LOGIN: 'FETCH_LOGIN',
    FETCH_REGISTER: 'FETCH_REGISTER',
    FETCH_IS_DM: 'FETCH_IS_DM',
    FETCH_REMOVE_PREMIUM_DM: 'FETCH_REMOVE_PREMIUM_DM',
    FETCH_BECOME_PREMIUM_DM: 'FETCH_BECOME_PREMIUM_DM'
}